# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rrust_wrappers", use_symbols = TRUE, package_name = "rrust")

#' @docType package
#' @usage NULL
#' @useDynLib rrust, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

#' Return string `"Hello world!"` to R.
#' @export
hello_worldd <- function() invisible(.Call(wrap__hello_worldd))


# nolint end
